grpc:
  enableReflection: true
  port: 6566
  security:
    auth:
      enabled: false
spring:
  cassandra:
    schema-action: create-if-not-exists
    keyspace-name: order_keyspace
    request:
      timeout: 10s
    connection:
      connect-timeout: 10s
      init-query-timeout: 10s
    local-datacenter: datacenter1
  security:
    oauth2:
      resourceserver:
        jwt.issuer-uri: https://accounts.google.com
        jwt.jwk-set-uri: https://www.googleapis.com/oauth2/v3/certs
apps:
  product-app:
    port: 6567
    host: localhost
  payment-app:
    port: 6565
    host: localhost
    duration: 10000
    credential: token
---

spring:
  config:
    activate:
      on-profile: prod
grpc:
  security:
    auth:
      enabled: true